initial commit
threesigmaxyz/starkex-data-availability-committee pull request #1
Opened 2023-02-19 12:48 UTC by JoseAfonsoThreeSigma

2023-02-22 17:27 UTC, JoseAfonsoThreeSigma commented on .github/workflows/pull_request.yml
> +#      - name: Run Unit tests
Having an hard time to have these tests running with CTest. Cmake and PyTest. Unless someone has experience with this, I would like to postpone this to another issue

2023-02-23 15:51 UTC, JoseAfonsoThreeSigma commented on src/starkware/storage/redis_storage.py
> +        self.connection = build_connection_string(os.getenv('REDIS_CONNSTR'), db)
This is only set on the charts. Does anyone have a simple way to override a field in the `config.yaml` file in the helm charts to avoid reading this from an env var?

2023-02-23 16:31 UTC, 3s-jorgematos commented on src/starkware/storage/redis_storage.py
> +        self.connection = build_connection_string(os.getenv('REDIS_CONNSTR'), db)
You can create a file from a configmap. Like this: https://carlos.mendible.com/2019/02/10/kubernetes-mount-file-pod-with-configmap/

You would have to add it in charts (configmap inside the templates), and the values on the values.yaml

2023-02-23 16:35 UTC, JoseAfonsoThreeSigma commented on src/starkware/storage/redis_storage.py
> +        self.connection = build_connection_string(os.getenv('REDIS_CONNSTR'), db)
With this solution, I would have to load the entire file from a volume right? I would prefer to only override some props but if that is not possible, I will move forward with your suggestion

2023-02-23 16:40 UTC, 3s-jorgematos requested changes
LGTM, just waiting for how to handle the redis con str config

2023-02-24 09:21 UTC, asynctomatic requested changes
Left a question regarding the reuse if Redis connections as well as some other minor comments.

2023-02-24 09:21 UTC, asynctomatic commented on src/starkware/storage/redis_storage.py
> +        r = Redis(
I think this is creating a new `ConnectionPool` every time a Redis command is executed. A solution for this would be to create the pool in the `RedisStorage` class constructor an pass it as an argument when instantiating the `Redis` class.

An example of this can be found here: https://fahadahammed.com/effective-use-of-redis-with-python-and-connection-pool/

2023-02-24 09:21 UTC, asynctomatic commented on src/starkware/storage/redis_storage.py
> +def build_connection_string(
nitpick: I asked GPT to make try and improve this code and this was the output:

=== GPT START ===
- Type hints are added to the function arguments and return value to make it easier to understand the expected inputs and outputs.
- Error handling is added for cases where the connection string is not in the expected format, or where a required option is missing.
- The code is made more concise by using dictionary comprehension to build the connection arguments dictionary.

```python
from typing import Dict
from redis import Connection

def build_connection_string(
        conn_str: str,
        db: int
) -> Connection:
    try:
        hostport, *options = conn_str.split(",")
        host, _, port = hostport.partition(":")
        arguments = {
            opt: int(value) if opt == "port" else value
            for opt, _, value in (option.partition("=") for option in options)
            if opt not in ("ssl", "abortConnect")
        }
    except (AttributeError, ValueError, TypeError):
        raise ValueError("Invalid connection string format")

    if not host:
        raise ValueError("Missing host in connection string")

    if not port:
        raise ValueError("Missing port in connection string")

    return Connection(host=host, port=int(port), db=db, **arguments)
```

In this version of the code, the try block is used to catch any exceptions that might occur when parsing the connection string. If an exception occurs, a `ValueError` is raised with an appropriate error message.

After parsing the connection string, two additional checks are added to ensure that the required `host` and `port` values are present. If either value is missing, a `ValueError` is raised with an appropriate error message.

Finally, dictionary comprehension is used to build the arguments dictionary in a more concise and readable way. The `if opt not in ("ssl", "abortConnect")` condition is used to exclude any options that should be ignored, such as `ssl` and `abortConnect`.
=== GPT END ===

This does not make much of a difference since the original code worked but either way I added it for completion. Nonetheless I think we should refactor this function to use connection pools if the other comment I left in this class regarding not reusing Redis connections is accurate.

2023-02-24 09:29 UTC, asynctomatic commented on src/starkware/storage/redis_storage.py
> +def build_connection_string(
Also, aren't we passing the `port` argument twice to the `Connection` constructor? Once explicitly (`port=int(port)`) and other using `*arguments`?

2023-02-24 11:09 UTC, JoseAfonsoThreeSigma commented on src/starkware/storage/redis_storage.py
> +        r = Redis(
Changed to only create a `ConnectionPool` once in the `RedisStorage` constructor

2023-02-24 11:12 UTC, JoseAfonsoThreeSigma commented on src/starkware/storage/redis_storage.py
> +def build_connection_string(
Changed. Regarding the port, it's not being passed twice because this splits the multiple connection string segments from the char `,` and the string has the following format: `starkex-ragnarok-redis-development.redis.cache.windows.net:6380,password=__=,ssl=True,abortConnect=False`

2023-02-24 11:14 UTC, 3s-jorgematos commented on src/starkware/storage/redis_storage.py
> +        self.connection = build_connection_string(os.getenv('REDIS_CONNSTR'), db)
Yes, not sure if python has a way to handle it like .NET with the environment variables override

2023-02-24 11:17 UTC, JoseAfonsoThreeSigma commented on src/starkware/committee/setup.py
> +        "PyYAML>=6.0",
I'm not sure how this `setup.py` works but I believe this enforces the necessary packages and respective versions to run this solution, whereas in the `requirements.txt` you choose the actual package version, which should comply with the constraints defined here. Still, as I'm not very sure of this, I changed all the requirements files to only accept the 6.0 version. In reality, any version bigger than 5.4.0 (which has a [critical vulnerability](https://security.snyk.io/vuln/SNYK-PYTHON-PYYAML-590151)) should work.

2023-02-24 11:23 UTC, JoseAfonsoThreeSigma commented on scripts/requirements-gen.txt
> +PyYAML
Changed to enforce the 6.0 version in every requirements file

2023-02-24 11:24 UTC, JoseAfonsoThreeSigma commented on .github/workflows/pull_request.yml
> +#      - name: Checkout Target Repository
Added it in the first place to follow the same approach used in the StarkExpress solution, where if in the future, we want to deploy dev versions to a separate k8s cluster, we could automate it with this step in the PRs CI. But since we are not using this anytime soon, deleted it anyway.

2023-02-24 11:33 UTC, JoseAfonsoThreeSigma commented on config.yml
> +    db: 2
Added new section here https://www.notion.so/three-sigma/Infrastructure-Documentation-c847fe3bf8ba481e8ca19fb2dc0c6a6e?pvs=4#4949b5aad5b14adda724fb580a08394d

2023-02-24 12:13 UTC, JoseAfonsoThreeSigma commented on src/starkware/storage/redis_storage.py
> +        self.connection = build_connection_string(os.getenv('REDIS_CONNSTR'), db)
We've talked on a call and decided to postpone this, as in order to read the redis conn str secret into a configMap volume, we would have to implement additional mechanisms to override the configMap secrets during the pipeline. Opening an issue to resolve this later.

2023-02-24 14:02 UTC, asynctomatic commented on src/starkware/committee/setup.py
> +        "PyYAML>=6.0",
I think the `setup.py` is what setuptools runs when installing a package (eg. via pip) and is independent from the `requirements.txt` file (more for setting up local dev environments or manual installations). Either way it's fixed now.

PS: you can actually include arbitrary code on the `setup.py` file that get's executed upon a `pip install` command, which can lead to some obvious security concerns: https://incolumitas.com/2016/06/08/typosquatting-package-managers/

2023-02-25 15:46 UTC, asynctomatic approved these changes

2023-02-27 10:10 UTC, 3s-jorgematos approved these changes

2023-02-27 13:13 UTC, merged